#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# auto source import every markdown documents
# @see https://www.npmjs.com/package/@handbook/markdown-source-import
yarn run markdown-source-import README.md --git-add

yarn run lint-staged
